import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { LoaderProvider } from "./context/LoaderContext";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LoaderProvider>
          <div className="min-h-screen bg-gray-50">
            <Navbar />
            {children}
          </div>
        </LoaderProvider>
      </body>
    </html>
  );
}
