import Link from "next/link"
import './globals.css'
import { Roboto} from 'next/font/google'

const roboto = Roboto({ weight: ['400','500', '600', '700'], subsets: ['latin'] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">    
      <body className={roboto.className}>
        <nav>
            <Link href={'/'}>Home</Link>
            <Link href={'/products'}>Products</Link>
            <Link href={'/file-upload'}>file upload</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
